site_name: PyDevices Documentation

repo_url: https://github.com/bdbarnett/mpdisplay/

copyright: "Copyright 2024, Brad Barnett"

docs_dir: docs

site_dir: site

theme:
  name: "material"

plugins:
- search
- autorefs
- gen-files:
    scripts:
    - .site_utils/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false
          show_bases: false
          inherited_members: true
          paths: [src/lib, src/lib/displays, src/lib/buses]
          docstring_style: google
          docstring_section_style: list
          # heading_level: 1


nav:
# rest of the navigation...
- Details:
  - Getting Started: GETTING-STARTED.md
  - Screenshots: SCREENSHOTS.md
  - Another Level:
    - And Another:
      - Test Page: test-page.md
# defer to gen-files + literate-nav
- Code Reference: reference/  
# rest of the navigation...

markdown_extensions:
  - toc:
      permalink: true
      separator: "_"
