site_name: "My Library"

theme:
  name: "material"

plugins:
- search
- autorefs
- gen-files:
    scripts:
    - .site_utils/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings

nav:
# rest of the navigation...
- project:
  - lorem: GETTING-STARTED.md
  - ipsum: test-page.md
# defer to gen-files + literate-nav
- Code Reference: reference/  
# rest of the navigation...