site_name: PyDevices Documentation

repo_url: https://github.com/bdbarnett/mpdisplay/

copyright: "Copyright 2024, Brad Barnett"

docs_dir: docs

site_dir: site

theme:
  name: "mkdocs"

plugins:
- search
- autorefs
- gen-files:
    scripts:
    - .site_utils/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings

nav:
# rest of the navigation...
- Details:
  - Getting Started: GETTING-STARTED.md
  - Another Level:
    - And Another:
      - Test Page: test-page.md
# defer to gen-files + literate-nav
- Code Reference: reference/  
# rest of the navigation...

markdown_extensions:
  - toc:
      permalink: true
      separator: "_"
