[files]
"../mpdisplay/board_config.py" = "/"
"../mpdisplay/path.py" = "/"
"../mpdisplay/app_configs/tft_config.py" = "/app_configs/"
"../mpdisplay/app_configs/lv_config.py" = "/app_configs/"
"../mpdisplay/app_configs/hardware_setup.py" = "/app_configs/"
"../mpdisplay/app_configs/color_setup.py" = "/app_configs/"

"../mpdisplay/lib/area.py" = "/lib/"
"../mpdisplay/lib/micropython.py" = "/lib/"
"../mpdisplay/lib/displays/_numpy.py" = "/lib/displays/"
"../mpdisplay/lib/displays/_viper.py" = "/lib/displays/"
"../mpdisplay/lib/displays/__init__.py" = "/lib/displays/"
"../mpdisplay/lib/displays/psdisplay/psdevices.py" = "/lib/displays/psdisplay/"
"../mpdisplay/lib/displays/psdisplay/__init__.py" = "/lib/displays/psdisplay/"
"../mpdisplay/lib/displays/__pycache__/_numpy.cpython-312.pyc" = "/lib/displays/__pycache__/"
"../mpdisplay/lib/displays/__pycache__/__init__.cpython-312.pyc" = "/lib/displays/__pycache__/"
"../mpdisplay/lib/displays/fbdisplay/__init__.py" = "/lib/displays/fbdisplay/"
"../mpdisplay/lib/displays/jndisplay/__init__.py" = "/lib/displays/jndisplay/"
"../mpdisplay/lib/displays/jndisplay/__pycache__/__init__.cpython-312.pyc" = "/lib/displays/jndisplay/__pycache__/"
"../mpdisplay/lib/displays/busdisplay/__init__.py" = "/lib/displays/busdisplay/"
"../mpdisplay/lib/displays/dtdisplay/__init__.py" = "/lib/displays/dtdisplay/"
"../mpdisplay/lib/displays/dtdisplay/__pycache__/__init__.cpython-312.pyc" = "/lib/displays/dtdisplay/__pycache__/"
"../mpdisplay/lib/displays/dtdisplay/pgdisplay/__init__.py" = "/lib/displays/dtdisplay/pgdisplay/"
"../mpdisplay/lib/displays/dtdisplay/sdldisplay/_poll.py" = "/lib/displays/dtdisplay/sdldisplay/"
"../mpdisplay/lib/displays/dtdisplay/sdldisplay/__init__.py" = "/lib/displays/dtdisplay/sdldisplay/"
"../mpdisplay/lib/displays/dtdisplay/sdldisplay/__pycache__/__init__.cpython-312.pyc" = "/lib/displays/dtdisplay/sdldisplay/__pycache__/"
"../mpdisplay/lib/displays/dtdisplay/sdldisplay/__pycache__/_poll.cpython-312.pyc" = "/lib/displays/dtdisplay/sdldisplay/__pycache__/"
"../mpdisplay/lib/displays/dtdisplay/sdldisplay/sdl2_lib/_constants.py" = "/lib/displays/dtdisplay/sdldisplay/sdl2_lib/"
"../mpdisplay/lib/displays/dtdisplay/sdldisplay/sdl2_lib/_cpython.py" = "/lib/displays/dtdisplay/sdldisplay/sdl2_lib/"
"../mpdisplay/lib/displays/dtdisplay/sdldisplay/sdl2_lib/_micropython.py" = "/lib/displays/dtdisplay/sdldisplay/sdl2_lib/"
"../mpdisplay/lib/displays/dtdisplay/sdldisplay/sdl2_lib/__init__.py" = "/lib/displays/dtdisplay/sdldisplay/sdl2_lib/"
"../mpdisplay/lib/displays/dtdisplay/sdldisplay/sdl2_lib/__pycache__/_cpython.cpython-312.pyc" = "/lib/displays/dtdisplay/sdldisplay/sdl2_lib/__pycache__/"
"../mpdisplay/lib/displays/dtdisplay/sdldisplay/sdl2_lib/__pycache__/__init__.cpython-312.pyc" = "/lib/displays/dtdisplay/sdldisplay/sdl2_lib/__pycache__/"
"../mpdisplay/lib/displays/dtdisplay/sdldisplay/sdl2_lib/__pycache__/_constants.cpython-312.pyc" = "/lib/displays/dtdisplay/sdldisplay/sdl2_lib/__pycache__/"

"../mpdisplay/lib/eventsys/events.py" = "/lib/eventsys/"
"../mpdisplay/lib/eventsys/devices.py" = "/lib/eventsys/"
"../mpdisplay/lib/eventsys/keys.py" = "/lib/eventsys/"
"../mpdisplay/lib/eventsys/__init__.py" = "/lib/eventsys/"
"../mpdisplay/lib/eventsys/__pycache__/keys.cpython-312.pyc" = "/lib/eventsys/__pycache__/"
"../mpdisplay/lib/eventsys/__pycache__/events.cpython-312.pyc" = "/lib/eventsys/__pycache__/"
"../mpdisplay/lib/eventsys/__pycache__/devices.cpython-312.pyc" = "/lib/eventsys/__pycache__/"
"../mpdisplay/lib/eventsys/__pycache__/__init__.cpython-312.pyc" = "/lib/eventsys/__pycache__/"

"../mpdisplay/lib/framebuf.py" = "/lib/"
"../mpdisplay/lib/graphics/_displaybuf_viper.py" = "/lib/graphics/"
"../mpdisplay/lib/graphics/shapes.py" = "/lib/graphics/"
"../mpdisplay/lib/graphics/displaybuf.py" = "/lib/graphics/"
"../mpdisplay/lib/graphics/__init__.py" = "/lib/graphics/"
"../mpdisplay/lib/graphics/framebuf_plus.py" = "/lib/graphics/"
"../mpdisplay/lib/graphics/__pycache__/framebuf_plus.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../mpdisplay/lib/graphics/__pycache__/shapes.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../mpdisplay/lib/graphics/__pycache__/__init__.cpython-312.pyc" = "/lib/graphics/__pycache__/"
"../mpdisplay/lib/graphics/binfont/binfont_8x16.bin" = "/lib/graphics/binfont/"
"../mpdisplay/lib/graphics/binfont/binfont_8x14.bin" = "/lib/graphics/binfont/"
"../mpdisplay/lib/graphics/binfont/binfont_8x8.bin" = "/lib/graphics/binfont/"
"../mpdisplay/lib/graphics/binfont/__init__.py" = "/lib/graphics/binfont/"
"../mpdisplay/lib/graphics/binfont/__pycache__/__init__.cpython-312.pyc" = "/lib/graphics/binfont/__pycache__/"

"../mpdisplay/lib/palettes/_cube125.py" = "/lib/palettes/"
"../mpdisplay/lib/palettes/_material_design.py" = "/lib/palettes/"
"../mpdisplay/lib/palettes/_cube8.py" = "/lib/palettes/"
"../mpdisplay/lib/palettes/cube.py" = "/lib/palettes/"
"../mpdisplay/lib/palettes/_cube27.py" = "/lib/palettes/"
"../mpdisplay/lib/palettes/material_design.py" = "/lib/palettes/"
"../mpdisplay/lib/palettes/_cube64.py" = "/lib/palettes/"
"../mpdisplay/lib/palettes/wheel.py" = "/lib/palettes/"
"../mpdisplay/lib/palettes/__init__.py" = "/lib/palettes/"
"../mpdisplay/lib/palettes/__pycache__/_material_design.cpython-312.pyc" = "/lib/palettes/__pycache__/"
"../mpdisplay/lib/palettes/__pycache__/material_design.cpython-312.pyc" = "/lib/palettes/__pycache__/"
"../mpdisplay/lib/palettes/__pycache__/__init__.cpython-312.pyc" = "/lib/palettes/__pycache__/"

"../mpdisplay/lib/showtimer.py" = "/lib/"
"../mpdisplay/lib/timer/_sdl2.py" = "/lib/timer/"
"../mpdisplay/lib/timer/_librt.py" = "/lib/timer/"
"../mpdisplay/lib/timer/_timerbase.py" = "/lib/timer/"
"../mpdisplay/lib/timer/__init__.py" = "/lib/timer/"
"../mpdisplay/lib/timer/__pycache__/_sdl2.cpython-312.pyc" = "/lib/timer/__pycache__/"
"../mpdisplay/lib/timer/__pycache__/_timerbase.cpython-312.pyc" = "/lib/timer/__pycache__/"
"../mpdisplay/lib/timer/__pycache__/__init__.cpython-312.pyc" = "/lib/timer/__pycache__/"

"../mpdisplay/extras/bitmap.py" = "/extras/"
"../mpdisplay/extras/wifi.py" = "/extras/"
"../mpdisplay/extras/ezfont.py" = "/extras/"
"../mpdisplay/extras/write.py" = "/extras/"
"../mpdisplay/extras/bmp565.py" = "/extras/"
"../mpdisplay/extras/touch_keypad.py" = "/extras/"
"../mpdisplay/extras/lv_mpdisplay.py" = "/extras/"
"../mpdisplay/extras/keypins.py" = "/extras/"
"../mpdisplay/extras/pbm.py" = "/extras/"
"../mpdisplay/extras/__pycache__/touch_keypad.cpython-312.pyc" = "/extras/__pycache__/"
"../mpdisplay/extras/pytext/_pytext_python.py" = "/extras/pytext/"
"../mpdisplay/extras/pytext/_pytext_viper.py" = "/extras/pytext/"
"../mpdisplay/extras/pytext/__init__.py" = "/extras/pytext/"
"../mpdisplay/extras/pytext/fonts/vga1_8x8.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/vga2_bold_16x16.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/vga2_bold_16x32.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/vga1_8x16.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/vga2_16x32.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/vga1_16x16.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/vga1_bold_16x32.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/vga2_16x16.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/vga1_16x32.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/vga2_8x16.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/vga1_bold_16x16.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/vga2_8x8.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/__init__.py" = "/extras/pytext/fonts/"
"../mpdisplay/extras/pytext/fonts/compile_upload.sh" = "/extras/pytext/fonts/"

