[files]
"../src/jupyter_notebook.ipynb" = "/"
"../src/path.py" = "/"
"../src/configs/board_config.py" = "/configs/"
"../src/configs/color_setup.py" = "/configs/"
"../src/configs/hardware_setup.py" = "/configs/"
"../src/configs/lv_config.py" = "/configs/"
"../src/configs/tft_config.py" = "/configs/"

"../src/extras/adafruit_ticks.py" = "/extras/"
"../src/extras/bmp565.py" = "/extras/"
"../src/extras/console.py" = "/extras/"
"../src/extras/ezfont.py" = "/extras/"
"../src/extras/keypins.py" = "/extras/"
"../src/extras/micropython.py" = "/extras/"
"../src/extras/pbm.py" = "/extras/"
"../src/extras/png.py" = "/extras/"
"../src/extras/tft_bitmap.py" = "/extras/"
"../src/extras/tft_write.py" = "/extras/"
"../src/extras/wifi.py" = "/extras/"
"../src/extras/tft_text/__init__.py" = "/extras/tft_text/"
"../src/extras/tft_text/_python.py" = "/extras/tft_text/"
"../src/extras/tft_text/_viper.py" = "/extras/tft_text/"
"../src/extras/tft_text/fonts/__init__.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/compile_upload.sh" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_8x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_8x8.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_bold_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga1_bold_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_16x32.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_8x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_8x8.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_bold_16x16.py" = "/extras/tft_text/fonts/"
"../src/extras/tft_text/fonts/vga2_bold_16x32.py" = "/extras/tft_text/fonts/"

"../src/lib/buses/spibus/__init__.py" = "/lib/buses/spibus/"

"../src/lib/buses/i80bus/__init__.py" = "/lib/buses/i80bus/"
"../src/lib/buses/i80bus/_gpio_pin.py" = "/lib/buses/i80bus/"
"../src/lib/buses/i80bus/_rp2_wip.py" = "/lib/buses/i80bus/"

"../src/lib/displays/basedisplay/__init__.py" = "/lib/displays/basedisplay/"
"../src/lib/displays/basedisplay/_area.py" = "/lib/displays/basedisplay/"
"../src/lib/displays/basedisplay/_numpy.py" = "/lib/displays/basedisplay/"
"../src/lib/displays/basedisplay/_viper.py" = "/lib/displays/basedisplay/"

"../src/lib/displays/busdisplay/__init__.py" = "/lib/displays/busdisplay/"

"../src/lib/displays/dtdisplay/__init__.py" = "/lib/displays/dtdisplay/"
"../src/lib/displays/dtdisplay/pgdisplay/__init__.py" = "/lib/displays/dtdisplay/pgdisplay/"
"../src/lib/displays/dtdisplay/sdldisplay/__init__.py" = "/lib/displays/dtdisplay/sdldisplay/"
"../src/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/__init__.py" = "/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/"
"../src/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/_constants.py" = "/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/"
"../src/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/_cpython.py" = "/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/"
"../src/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/_micropython.py" = "/lib/displays/dtdisplay/sdldisplay/_sdl2_lib/"

"../src/lib/displays/fbdisplay/__init__.py" = "/lib/displays/fbdisplay/"

"../src/lib/displays/jndisplay/__init__.py" = "/lib/displays/jndisplay/"

"../src/lib/displays/psdisplay/__init__.py" = "/lib/displays/psdisplay/"

"../src/lib/eventsys/__init__.py" = "/lib/eventsys/"
"../src/lib/eventsys/devices.py" = "/lib/eventsys/"
"../src/lib/eventsys/events.py" = "/lib/eventsys/"
"../src/lib/eventsys/keys.py" = "/lib/eventsys/"
"../src/lib/eventsys/touch_keypad.py" = "/lib/eventsys/"

"../src/lib/framebuf.py" = "/lib/"
"../src/lib/gfx/__init__.py" = "/lib/gfx/"
"../src/lib/gfx/shapes/__init__.py" = "/lib/gfx/shapes/"
"../src/lib/gfx/displaybuf/__init__.py" = "/lib/gfx/displaybuf/"
"../src/lib/gfx/displaybuf/_viper.py" = "/lib/gfx/displaybuf/"
"../src/lib/gfx/framebuf_plus/__init__.py" = "/lib/gfx/framebuf_plus/"
"../src/lib/gfx/binfont/__init__.py" = "/lib/gfx/binfont/"
"../src/lib/gfx/binfont/binfont_8x14.bin" = "/lib/gfx/binfont/"
"../src/lib/gfx/binfont/binfont_8x16.bin" = "/lib/gfx/binfont/"
"../src/lib/gfx/binfont/binfont_8x8.bin" = "/lib/gfx/binfont/"

"../src/lib/palettes/__init__.py" = "/lib/palettes/"
"../src/lib/palettes/_cube125.py" = "/lib/palettes/"
"../src/lib/palettes/_cube27.py" = "/lib/palettes/"
"../src/lib/palettes/_cube64.py" = "/lib/palettes/"
"../src/lib/palettes/_cube8.py" = "/lib/palettes/"
"../src/lib/palettes/_material_design.py" = "/lib/palettes/"
"../src/lib/palettes/cube.py" = "/lib/palettes/"
"../src/lib/palettes/material_design.py" = "/lib/palettes/"
"../src/lib/palettes/wheel.py" = "/lib/palettes/"

"../src/lib/timer/__init__.py" = "/lib/timer/"
"../src/lib/timer/_librt.py" = "/lib/timer/"
"../src/lib/timer/_sdl2.py" = "/lib/timer/"
"../src/lib/timer/_timerbase.py" = "/lib/timer/"

