[files]
"../board_config.py" = "/"
"../path.py" = "/"
"../app_configs/color_setup.py" = "/app_configs/"
"../app_configs/lv_config.py" = "/app_configs/"
"../app_configs/tft_config.py" = "/app_configs/"
"../app_configs/mpdisplay.toml" = "/app_configs/"
"../app_configs/hardware_setup.py" = "/app_configs/"

"../lib/area.py" = "/lib/"
"../lib/micropython.py" = "/lib/"
"../lib/displays/_viper.py" = "/lib/displays/"
"../lib/displays/_numpy.py" = "/lib/displays/"
"../lib/displays/__init__.py" = "/lib/displays/"
"../lib/displays/busdisplay/__init__.py" = "/lib/displays/busdisplay/"
"../lib/displays/fbdisplay/__init__.py" = "/lib/displays/fbdisplay/"
"../lib/displays/psdisplay/psdevices.py" = "/lib/displays/psdisplay/"
"../lib/displays/psdisplay/__init__.py" = "/lib/displays/psdisplay/"
"../lib/displays/dtdisplay/__init__.py" = "/lib/displays/dtdisplay/"
"../lib/displays/dtdisplay/sdldisplay/_poll.py" = "/lib/displays/dtdisplay/sdldisplay/"
"../lib/displays/dtdisplay/sdldisplay/__init__.py" = "/lib/displays/dtdisplay/sdldisplay/"
"../lib/displays/dtdisplay/sdldisplay/sdl2_lib/_cpython.py" = "/lib/displays/dtdisplay/sdldisplay/sdl2_lib/"
"../lib/displays/dtdisplay/sdldisplay/sdl2_lib/_micropython.py" = "/lib/displays/dtdisplay/sdldisplay/sdl2_lib/"
"../lib/displays/dtdisplay/sdldisplay/sdl2_lib/__init__.py" = "/lib/displays/dtdisplay/sdldisplay/sdl2_lib/"
"../lib/displays/dtdisplay/sdldisplay/sdl2_lib/_constants.py" = "/lib/displays/dtdisplay/sdldisplay/sdl2_lib/"
"../lib/displays/dtdisplay/pgdisplay/__init__.py" = "/lib/displays/dtdisplay/pgdisplay/"
"../lib/displays/jndisplay/__init__.py" = "/lib/displays/jndisplay/"

"../lib/eventsys/keys.py" = "/lib/eventsys/"
"../lib/eventsys/events.py" = "/lib/eventsys/"
"../lib/eventsys/__init__.py" = "/lib/eventsys/"
"../lib/eventsys/devices.py" = "/lib/eventsys/"

"../lib/framebuf.py" = "/lib/"
"../lib/graphics/_displaybuf_viper.py" = "/lib/graphics/"
"../lib/graphics/shapes.py" = "/lib/graphics/"
"../lib/graphics/displaybuf.py" = "/lib/graphics/"
"../lib/graphics/__init__.py" = "/lib/graphics/"
"../lib/graphics/framebuf_plus.py" = "/lib/graphics/"
"../lib/graphics/binfont/binfont_8x14.bin" = "/lib/graphics/binfont/"
"../lib/graphics/binfont/binfont_8x8.bin" = "/lib/graphics/binfont/"
"../lib/graphics/binfont/__init__.py" = "/lib/graphics/binfont/"
"../lib/graphics/binfont/binfont_8x16.bin" = "/lib/graphics/binfont/"

"../lib/palettes/_material_design.py" = "/lib/palettes/"
"../lib/palettes/_cube8.py" = "/lib/palettes/"
"../lib/palettes/wheel.py" = "/lib/palettes/"
"../lib/palettes/_cube64.py" = "/lib/palettes/"
"../lib/palettes/_cube27.py" = "/lib/palettes/"
"../lib/palettes/material_design.py" = "/lib/palettes/"
"../lib/palettes/_cube125.py" = "/lib/palettes/"
"../lib/palettes/__init__.py" = "/lib/palettes/"
"../lib/palettes/cube.py" = "/lib/palettes/"

"../lib/showtimer.py" = "/lib/"
"../lib/timer/_librt.py" = "/lib/timer/"
"../lib/timer/_timerbase.py" = "/lib/timer/"
"../lib/timer/_sdl2.py" = "/lib/timer/"
"../lib/timer/__init__.py" = "/lib/timer/"

