[files]
"../examples/mpdisplay_simpletest.py" = "/examples/"
"../examples/mpdisplay_event_test.py" = "/examples/"
"../examples/mpdisplay_logo.py" = "/examples/"
"../examples/mpdisplay_touch_test.py" = "/examples/"
"../examples/paint.py" = "/examples/"
"../examples/calculator.py" = "/examples/"

"../extras/touch_keypad.py" = "/extras/"

"../path.py" = "/"
"../board_config.py" = "/"

"../lib/area.py" = "/lib/"
"../lib/framebuf.py" = "/lib/"
"../lib/micropython.py" = "/lib/"

"../lib/displays/__init__.py" = "/lib/displays/"
"../lib/displays/_viper.py" = "/lib/displays/"
"../lib/displays/_numpy.py" = "/lib/displays/"
"../lib/displays/psdisplay/__init__.py" = "/lib/displays/psdisplay/"
"../lib/displays/psdisplay/psdevices.py" = "/lib/displays/psdisplay/"

"../lib/eventsys/__init__.py" = "/lib/eventsys/"
"../lib/eventsys/events.py" = "/lib/eventsys/"
"../lib/eventsys/devices.py" = "/lib/eventsys/"
"../lib/eventsys/keys.py" = "/lib/eventsys/"

"../lib/palettes/__init__.py" = "/lib/palettes/"
"../lib/palettes/_material_design.py" = "/lib/palettes/"
"../lib/palettes/material_design.py" = "/lib/palettes/"
"../lib/palettes/_cube8.py" = "/lib/palettes/"
"../lib/palettes/_cube27.py" = "/lib/palettes/"
"../lib/palettes/_cube64.py" = "/lib/palettes/"
"../lib/palettes/_cube125.py" = "/lib/palettes/"
"../lib/palettes/cube.py" = "/lib/palettes/"
"../lib/palettes/wheel.py" = "/lib/palettes/"

"../lib/graphics/__init__.py" = "/lib/graphics/"
"../lib/graphics/_displaybuf_viper.py" = "/lib/graphics/"
"../lib/graphics/displaybuf.py" = "/lib/graphics/"
"../lib/graphics/framebuf_plus.py" = "/lib/graphics/"
"../lib/graphics/shapes.py" = "/lib/graphics/"
"../lib/graphics/binfont/__init__.py" = "/lib/graphics/binfont/"
"../lib/graphics/binfont/binfont_8x8.bin" = "/lib/graphics/binfont/"
"../lib/graphics/binfont/binfont_8x14.bin" = "/lib/graphics/binfont/"
"../lib/graphics/binfont/binfont_8x16.bin" = "/lib/graphics/binfont/"

