[files]
"examples/mpdisplay_simpletest.py" = ""
"examples/mpdisplay_event_test.py" = ""
"examples/mpdisplay_logo.py" = ""
"examples/mpdisplay_touch_test.py" = ""
"path.py" = ""
"board_config.py" = ""
"lib/area.py" = "lib/area.py"
"lib/framebuf.py" = "lib/framebuf.py"
"lib/micropython.py" = "lib/micropython.py"
"lib/mpdisplay/__init__.py" = "lib/mpdisplay/__init__.py"
"lib/mpdisplay/_viper.py" = "lib/mpdisplay/_viper.py"
"lib/mpdisplay/_numpy.py" = "lib/mpdisplay/_numpy.py"
"lib/mpdisplay/psdisplay/__init__.py" = "lib/mpdisplay/psdisplay/__init__.py"
"lib/mpdisplay/psdisplay/psdevices.py" = "lib/mpdisplay/psdisplay/psdevices.py"
"lib/eventsys/__init__.py" = "lib/eventsys/__init__.py"
"lib/eventsys/events.py" = "lib/eventsys/events.py"
"lib/eventsys/devices.py" = "lib/eventsys/devices.py"
"lib/eventsys/keys.py" = "lib/eventsys/keys.py"
"lib/palettes/__init__.py" = "lib/palettes/__init__.py"
"lib/palettes/_material_design.py" = "lib/palettes/_material_design.py"
"lib/palettes/material_design.py" = "lib/palettes/material_design.py"
"lib/palettes/_cube8.py" = "lib/palettes/_cube8.py"
"lib/palettes/_cube27.py" = "lib/palettes/_cube27.py"
"lib/palettes/_cube64.py" = "lib/palettes/_cube64.py"
"lib/palettes/_cube125.py" = "lib/palettes/_cube125.py"
"lib/palettes/cube.py" = "lib/palettes/cube.py"
"lib/palettes/wheel.py" = "lib/palettes/wheel.py"
"lib/graphics/__init__.py" = "lib/graphics/__init__.py"
"lib/graphics/_displaybuf_viper.py" = "lib/graphics/_displaybuf_viper.py"
"lib/graphics/displaybuf.py" = "lib/graphics/displaybuf.py"
"lib/graphics/framebuf_plus.py" = "lib/graphics/framebuf_plus.py"
"lib/graphics/shapes.py" = "lib/graphics/shapes.py"
"lib/graphics/binfont/__init__.py" = "lib/graphics/binfont/__init__.py"
"lib/graphics/binfont/binfont_8x8.bin" = "lib/graphics/binfont/binfont_8x8.bin"
"lib/graphics/binfont/binfont_8x14.bin" = "lib/graphics/binfont/binfont_8x14.bin"
"lib/graphics/binfont/binfont_8x16.bin" = "lib/graphics/binfont/binfont_8x16.bin"

